name: Karate Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: Karate-API/k-Api
        run: mvn clean install

      - name: Run Karate Tests
        working-directory: Karate-API/k-Api
        run: mvn test -Dkarate.options="classpath:src/test/java/features"
